# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Glab < Formula
  desc "A CLI tool for GitLab, similar to GitHub CLI (gh)"
  homepage "https://philipkram.github.io/Gitlab-CLI/"
  version "0.0.8"
  license "MIT"

  depends_on "git"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/PhilipKram/Gitlab-CLI/releases/download/v0.0.8/glab_0.0.8_darwin_amd64.tar.gz"
      sha256 "974523e05202be9b2b54c44734ded3b318337567f9a25aad916bab1557c908fd"

      def install
        bin.install "glab"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/PhilipKram/Gitlab-CLI/releases/download/v0.0.8/glab_0.0.8_darwin_arm64.tar.gz"
      sha256 "80f451b932fa323388b7f43b7e28978e8dc26ff0d833d31fef27a46f16b21e8b"

      def install
        bin.install "glab"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/PhilipKram/Gitlab-CLI/releases/download/v0.0.8/glab_0.0.8_linux_amd64.tar.gz"
      sha256 "6cc4fd735cbc9c8e8f3a950e364c47803ccff5c9498bf6fc8fe9169f2793c788"
      def install
        bin.install "glab"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/PhilipKram/Gitlab-CLI/releases/download/v0.0.8/glab_0.0.8_linux_arm64.tar.gz"
      sha256 "7410b1a04edb08b01eedd4f46372bd0473a9750c010f2f6edb8cd337c5c9da8a"
      def install
        bin.install "glab"
      end
    end
  end

  test do
    assert_match "glab version", shell_output("#{bin}/glab --version")
  end
end
