# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Glab < Formula
  desc "A CLI tool for GitLab, similar to GitHub CLI (gh)"
  homepage "https://philipkram.github.io/Gitlab-CLI/"
  version "0.0.4"
  license "MIT"

  depends_on "git"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/PhilipKram/Gitlab-CLI/releases/download/v0.0.4/glab_0.0.4_darwin_amd64.tar.gz"
      sha256 "52de07013a507666598f679692662d0c13ebbff87913dc7eb7df7423cc480ea8"

      def install
        bin.install "glab"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/PhilipKram/Gitlab-CLI/releases/download/v0.0.4/glab_0.0.4_darwin_arm64.tar.gz"
      sha256 "08e22e4364ea66f1a3caafe98fcc9ea53189113a864c3d2869d277c973c24282"

      def install
        bin.install "glab"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/PhilipKram/Gitlab-CLI/releases/download/v0.0.4/glab_0.0.4_linux_amd64.tar.gz"
      sha256 "bf2f94f5b797278ee2b8420f164349df86f852d8b97693ff06fd5bccb2abcac1"
      def install
        bin.install "glab"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/PhilipKram/Gitlab-CLI/releases/download/v0.0.4/glab_0.0.4_linux_arm64.tar.gz"
      sha256 "d72bd14302780b68beecb3559af1e2187bbb2e8d86f7acf6f43bd41b907eb623"
      def install
        bin.install "glab"
      end
    end
  end

  test do
    assert_match "glab version", shell_output("#{bin}/glab --version")
  end
end
