version: 2

project_name: glab

before:
  hooks:
    - go mod tidy
    - go vet ./...

builds:
  - id: glab
    main: .
    binary: glab
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - id: glab-archive
    ids:
      - glab
    formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats:
          - zip
    files:
      - README.md
      - LICENSE

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"

homebrew_casks:
  - name: glab
    ids:
      - glab-archive
    binaries:
      - glab
    repository:
      owner: PhilipKram
      name: Gitlab-CLI
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    directory: Casks
    homepage: "https://philipkram.github.io/Gitlab-CLI/"
    description: "A CLI tool for GitLab, similar to GitHub CLI (gh)"
    dependencies:
      - formula: git

nfpms:
  - id: glab-nfpm
    package_name: glab
    vendor: PhilipKram
    homepage: "https://philipkram.github.io/Gitlab-CLI/"
    maintainer: "PhilipKram"
    description: "A CLI tool for GitLab, similar to GitHub CLI (gh)"
    license: MIT
    formats:
      - deb
      - rpm
    bindir: /usr/bin

release:
  github:
    owner: PhilipKram
    name: Gitlab-CLI
  draft: false
  prerelease: auto
  name_template: "v{{ .Version }}"
